# baseurl = "https://seattlemahjong.com/"
baseurl = ""
title = "Seattle Riichi Mahjong Club"
theme = "cleanwhite"
languageCode = "en-us"

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "/images/preview.jpg"
  SEOTitle ="Seattle Riichi Mahjong"
  description = "Seattle Riichi Mahjong Club"
  keyword = "Seattle, mahjong, riichi mahjong"
  slogan = ""
  showtoc = false
  preserveTaxonomyNames = true
  logo = "/images/SRMC-logo.png"

  image_404 = "/images/SRMC-logo.png"
  title_404 = "Not found :("

  # Sidebar settings
  sidebar_about_description = "Seattle Riichi Mahjong Club"
  sidebar_avatar = "images/SRMC-logo.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false 
  featured_condition_size = 2 

  [params.social]
  meetup         = "https://www.meetup.com/SeattleRiichiMahjongClub/"
  rss            = false 
  email          = "contact@seattlemahjong.com"
  facebook      = "https://www.facebook.com/groups/SeattleMahjong"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/SeattleMahjong"
  #linkedin       = "full profile url in linkedin"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/BlaiseRitchie/SeattleMahjong"
  #wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  title = "Club Leaderboard and Players"
  href =  "https://seattlemahjong.club"
  [[params.friend_link]]
  title = "Tournament Mahjong"
  href =  "https://tomas.seattlemahjong.club"

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
